### ISSUE TITLE
Pre_processing error

### ISSUE THREAD

**Issue by JLTrincado** [ykat0/capital#1]
Dear authors,

I just read your preprint in biorxiv and I was excited to test your method on our 10x data. I follow the installation instructions and run the first step but I get the following error:

```
/home/trincadojl/Software/capital-0.1.14/pre_capital.py ./filtered_feature_bc_matrix.h5 
Traceback (most recent call last):
  File "/home/trincadojl/Software/capital-0.1.14/pre_capital.py", line 39, in <module>
    adata = preprocess.read_file(args.data, transpose=args.transpose)
  File "/home/trincadojl/Software/capital-0.1.14/main.py", line 40, in read_file
    return adata
UnboundLocalError: local variable 'adata' referenced before assignment
```

Why could be this happening?
Thanks for your time.

Best,
Juan L.

**Comment by ykat0** [comment]
Dear Juan,

Thank you for your interest in our work.
We will fix bugs including this error and release an update soon.

BW,

Yuki

**Comment by ykat0** [comment]
Dear Juan,

We have released an update where a new function has been added for 10x-MTX directory input in pre_capital.py. However, we have not addressed the issue of the H5-formatted input because it is a bit complicated for the current option parse. Instead, you can use Scanpy with scanpy.read_10x_h5 and adata.write to make an input compatible with CAPITAL.

Cheers,

Yuki
